# Generated by Django 2.2.6 on 2019-10-20 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='thumbnail',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='movies',
            name='video_link',
            field=models.URLField(max_length=1000, null=True),
        ),
    ]
